services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile    
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10
  nats-streaming:
    image: "nats-streaming"
    ports:
      - "4222:4222"

volumes:
  pgdata:
